---
services:
  pv204_memory_analysis:
    image: valorcz/pv204_memory_analysis:latest
    container_name: memory_analysis
    volumes:
      - data:/opt/vagrant
      - ./symbols:/home/vagrant/.local/share/volatility3/symbols:ro

volumes:
  data:
