---
services:
  pv204_memory_analysis:
    image: valorcz/pv204_memory_analysis
    container_name: memory_analysis
    # platform: linux/amd64
    build: .
    volumes:
      - data:/opt/vagrant

volumes:
  data:
